version: '3.1'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: collections-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MYSQL_DSN: "app:app@tcp(db:3306)/app"
      JWT_SECRET: "jwt_secret"
      JWT_REFRESH_SECRET: "jwt_refresh_secret"

  migrate:
    build:
      context: .
      dockerfile: build/Dockerfile.migrate
    container_name: migrate
    entrypoint: [
      "migrate",
      "-path", "/migrations",
      "-database", "mysql://app:app@tcp(db:3306)/app",
      "up"
    ]
    depends_on:
      - db
